import sys
import os
# Force Streamlit to recognize the main 'acss-core' folder
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

import streamlit as st
from src.agents.workflow import build_workflow

# 1. Setup the Web Page
st.set_page_config(page_title="ACSS Dashboard", layout="wide")

# 1. Setup the Web Page
st.set_page_config(page_title="ACSS Dashboard", layout="wide")
st.title("🛡️ Autonomous Clinical Scribe System")
st.markdown("### Human-in-the-Loop Validation Interface")

# 2. Initialize the AI Pipeline
@st.cache_resource
def get_pipeline():
    return build_workflow()

app = get_pipeline()

# 3. Build the Sidebar (For Input)
st.sidebar.header("1. Input Transcript")
st.sidebar.info("In a live hospital setting, WhisperX would auto-fill this box from the doctor's microphone.")

transcript_input = st.sidebar.text_area(
    "Raw Audio Transcript (Arabizi/English):",
    value="Al mareed came in complaining of a severe headache. BP is 120/80.",
    height=200
)

# 4. Run the Pipeline from the UI
if st.sidebar.button("Run AI Pipeline", type="primary"):
    with st.spinner("🤖 Running Multi-Agent AI Pipeline..."):
        
        # Package the starting state
        initial_state = {
            "transcript": transcript_input,
            "extracted_facts": {},
            "soap_note": "",
            "validation_flags": [],
            "final_approved": False
        }
        
        # Send it through LangGraph
        final_state = app.invoke(initial_state)
        
        # Save the result so the screen doesn't refresh and lose it
        st.session_state["result"] = final_state

# 5. Build the Main Interface (For Review)
if "result" in st.session_state:
    state = st.session_state["result"]
    
    # Create two side-by-side columns
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("📝 Drafted SOAP Note")
        # Notice this is a text_area, allowing the doctor to manually edit it!
        edited_note = st.text_area(
            "Review and Edit (Required before EHR sync):", 
            value=state["soap_note"], 
            height=300
        )
        
        if st.button("✅ Approve & Send to EHR", type="primary"):
            st.success("Note Approved! Data successfully locked and synced to mocked EHR.")
            st.balloons() # A fun little visual reward for testing
            
    with col2:
        st.subheader("🛡️ Validator Audit & Codes")
        # Display the flags and ICD-10 codes generated by Agent 3
        for flag in state["validation_flags"]:
            if "Error" in flag or "RED FLAG" in flag:
                st.error(flag)
            else:
                st.info(flag)
                
        st.markdown("---")
        st.subheader("JSON Extracted Facts")
        # Display the raw data from Agent 1
        st.json(state["extracted_facts"])